version: "3"

services:
  backend:
    build: .
    container_name: app_elections-backend
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
