version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: appelections
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
